# Generated by Django 5.1.6 on 2025-02-19 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('ChapterID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('ChapterName', models.CharField(max_length=255)),
                ('TargetDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('DateofJoining', models.DateField()),
                ('Phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('ExamID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('ExamName', models.CharField(max_length=255)),
                ('DateOfExam', models.DateField()),
                ('Chapters', models.ManyToManyField(blank=True, to='apigateway.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('TID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apigateway.teacher')),
                ('Password', models.CharField(max_length=255)),
                ('Type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('ClassroomID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ClassTeacherID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apigateway.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('ModuleID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('ModuleName', models.CharField(max_length=255)),
                ('RemainingTime', models.IntegerField(help_text='Number of teaching hours required')),
                ('URL', models.URLField(blank=True, null=True)),
                ('ThisWeek', models.BooleanField(default=False)),
                ('ChapterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('DateofJoining', models.DateField()),
                ('GuardianName', models.CharField(max_length=255)),
                ('GuardianRelation', models.CharField(max_length=100)),
                ('GuardianPhone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('ClassroomID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apigateway.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('MarksID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('Marks', models.IntegerField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.exam')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.student')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='SubjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.subject'),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('SyllabusID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('ClassroomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.classroom')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.subject')),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='SyllabusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.syllabus'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='SyllabusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.syllabus'),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('TimeTableID', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.CharField(max_length=10)),
                ('Slot', models.IntegerField()),
                ('ClassroomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.classroom')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Status', models.IntegerField(default=0)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.student')),
            ],
            options={
                'unique_together': {('StudentID', 'Date')},
            },
        ),
    ]
