# Generated by Django 5.1.6 on 2025-02-16 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('TID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=255)),
                ('Type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectId', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
