# Generated by Django 5.1.6 on 2025-02-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='SubjectId',
            new_name='SubjectID',
        ),
    ]
