# Generated by Django 5.1.6 on 2025-02-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0002_rename_tid_logininfo_teacherid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='SyllabusID',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
