# Generated by Django 5.1.6 on 2025-02-16 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0002_rename_subjectid_subject_subjectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('DateofJoining', models.DateField()),
                ('Phone', models.CharField(max_length=15, unique=True)),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='TID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apigateway.teacher'),
        ),
    ]
