# Generated by Django 5.1.6 on 2025-02-16 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0004_classroom_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='ClassroomID',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='ClassroomID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apigateway.classroom'),
        ),
    ]
