# Generated by Django 5.1.6 on 2025-02-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0005_alter_classroom_classroomid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ClassroomID',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
