# Generated by Django 5.1.6 on 2025-02-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0006_remove_student_classroomid_delete_classroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('ClassroomID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ClassTeacherID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apigateway.teacher')),
            ],
        ),
    ]
