# Generated by Django 5.1.6 on 2025-02-16 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0008_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Status', models.IntegerField(default=0)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.student')),
            ],
            options={
                'unique_together': {('StudentID', 'Date')},
            },
        ),
    ]
