# Generated by Django 5.1.6 on 2025-02-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0009_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('TimeTableID', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.CharField(max_length=10)),
                ('Slot', models.IntegerField()),
                ('ClassroomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.classroom')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.subject')),
            ],
        ),
    ]
