# Generated by Django 5.1.6 on 2025-02-17 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0010_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('SyllabusID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('ClassroomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.classroom')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.subject')),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.teacher')),
            ],
        ),
    ]
