# Generated by Django 5.1.6 on 2025-02-17 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0011_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('ChapterID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('ChapterName', models.CharField(max_length=255)),
                ('TargetDate', models.DateField()),
                ('SyllabusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.syllabus')),
            ],
        ),
    ]
