# Generated by Django 5.1.6 on 2025-02-17 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0012_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('ModuleID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('ModuleName', models.CharField(max_length=255)),
                ('RemainingTime', models.IntegerField(help_text='Number of teaching hours required')),
                ('URL', models.URLField(blank=True, null=True)),
                ('ThisWeek', models.BooleanField(default=False)),
                ('ChapterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.chapter')),
            ],
        ),
    ]
