# Generated by Django 5.1.6 on 2025-02-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0013_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('ExamID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ExamName', models.CharField(max_length=255)),
                ('DateOfExam', models.DateField()),
                ('SyllabusID', models.CharField(max_length=100)),
                ('Chapters', models.ManyToManyField(related_name='exams', to='apigateway.chapter')),
            ],
        ),
    ]
