# Generated by Django 5.1.6 on 2025-02-17 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0014_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='Chapters',
            field=models.ManyToManyField(blank=True, to='apigateway.chapter'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ExamID',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='SyllabusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.syllabus'),
        ),
    ]
