# Generated by Django 5.1.6 on 2025-02-17 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0015_alter_exam_chapters_alter_exam_examid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('MarksID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('Marks', models.IntegerField()),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.exam')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.student')),
            ],
        ),
    ]
